### ISSUE TITLE
Box-mobile initial set up

### ISSUE THREAD

**Issue by khoatran2320** [khoatran2320/Senior-Design#46]
Implement box-mobile initial set up through barcode scanning.

**Comment by myliang47** [comment]
Put button on the dashboard for set up. When the user press on it, the app makes a call to the server to request an ID, the app gets the ID and presents it as a QR code.

(Later: embed wifi named and password in QR code)

**Comment by myliang47** [comment]
WiFi setup is done, should we close this?
